### ISSUE TITLE
GFE 2.4.5.54 compatibility

### ISSUE THREAD

**Issue by cgutman** [GTMoogle/StreamTheater#2]
There's a pairing compatibility issue with the newest GFE beta. 

This commit resolves it. https://github.com/moonlight-stream/moonlight-android/commit/1cb7727dc78fb465ee8106d1b010d4a582fe36b6

Just grab the jar from the repo and make that ComputerManagerService change and you're good.

The common change if you're curious: https://github.com/moonlight-stream/moonlight-common/commit/b7ccebe5e66875d9e578c1593d4a02bef506dbde

**Comment by GTMoogle** [comment]
Updated and released, thanks!
