### ISSUE TITLE
Investigate hardware decoder timestamp issue on 5.1

### ISSUE THREAD

**Issue by cgutman** [GTMoogle/StreamTheater#3]
My S6 got the 5.1.1 update today. Got an APK that doesn't do the Lollipop hack that I can try?

**Comment by GTMoogle** [comment]
According to the checkin history and the date on this file (5/21), this
should be before the software encoder work:
https://www.dropbox.com/s/qsfwp12pc634ebz/StreamTheaterMouseController.apk?dl=0

**Comment by cgutman** [comment]
The issue still exists on 5.1.1.
