### ISSUE TITLE
Moonlight Sync (GFE 2.5.11.45 and Razer Serval support)

### ISSUE THREAD

**Issue by cgutman** [GTMoogle/StreamTheater#5]
I had reports of Note 4 video performance degradation with GFE 2.5.11.45 on Moonlight, so I imagine you probably want to merge the fix into SteamTheater. It would be interesting to see if you can also confirm the degradation with the old code.

https://github.com/moonlight-stream/moonlight-android/commit/1e70e1d329c0ee61f1086df16bb6cf6c665c90ba

I also added support for the Razer Serval controller to the controller handling code, if you want to merge that too while you're at it.

https://github.com/moonlight-stream/moonlight-android/commit/e02a0096359ad9d697bf25bd3e569401a6880e1c

**Comment by GTMoogle** [comment]
Was there a bug report or documentation on the performance issue for me to refer to?  I haven't particularly noticed a problem so I'd like to know what to look for to confirm it.

**Comment by cgutman** [comment]
Not really. Other than the obvious issue where video is completely broken on Fire TV Stick, it's mostly increased latency reported by users (from Moonlight's toast at the end of the stream).

http://forum.xda-developers.com/showpost.php?p=61912424&postcount=2703

**Comment by GTMoogle** [comment]
Integrated.  Took a while because of other un-checked in changes.
