### ISSUE TITLE
GFE 2.8 compatibility update required

### ISSUE THREAD

**Issue by cgutman** [GTMoogle/StreamTheater#6]
GFE beta 2.8 changed some things in how running apps are indicated and how games are launched. Moonlight common is updated to support it, but you'll probably need to merge in the rest of the Moonlight Android changes because there's an API change in common to support 5.1 surround sound.

**Comment by GTMoogle** [comment]
Thanks.  I meant to get to it this weekend but the time never
materialized.  I'll see if I can do it this week.

**Comment by cgutman** [comment]
FYI, GFE 2.8 is in production now. There are app launching issues until you update.

**Comment by GTMoogle** [comment]
Thanks, I finally kicked myself into getting this done.  Hopefully updating SideloadVR is less painful... >_>
