### ISSUE TITLE
StreamTheater options menu w/o head-tracking

### ISSUE THREAD

**Issue by BriceJeanne** [GTMoogle/StreamTheater#8]
Hello, 

i'm using your application without a gear vr (developer mode and Homido V2 ) 
and sadly i can't change any settings because (i suppose) the application is using the Gear's sensors to head-track.

This is actually strange because head-tracking works on Occulus Home but not on Stream Theater.

I'm not asking you to make your application work with the phone's sensor, but perhaps to add a way to change the settings without head-tracking.

Also i'm a computer sciences student, and if you can't do it, perhaps you could give me some hints on doing it myself ?

Thanks.

**Comment by GTMoogle** [comment]
It's using a rather out of date version of the oculus SDK, which is why this problem exists.  It's something that needs to be updated anyway, but it's a pretty sizable chunk of work, and I haven't had the time to start on it.

**Comment by BriceJeanne** [comment]
Thanks for answering so quick, perhaps i will try to do it by myself.
